version: '3.8'

services:
  dev:
    image: python:3.12-slim
    container_name: blogbot-dev
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: bash -c "./scripts/setup-dev.sh && echo 'Container ready - logs visible in Docker Desktop' && tail -f /dev/null"
    profiles:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    image: python:3.12-slim
    container_name: blogbot-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: bash -c "./scripts/setup-dev.sh && poetry run python -m app.main"
    profiles:
      - app