version: '3.8'

services:
  dev:
    image: python:3.12-slim
    container_name: blogbot-dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: tail -f /dev/null
    profiles:
      - dev

  app:
    image: python:3.12-slim
    container_name: blogbot-app
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: poetry run python -m app.main
    profiles:
      - app
    depends_on:
      - dev